spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 60000

  jpa:
    show-sql: true

service:
  frontend:
    url: ${FRONTEND_SERVICE_URL:http://localhost:8080}
  ai:
    url: ${AI_SERVICE_URL:http://localhost:8082}
    secret-key: ${AI_BACKEND_KEY}
  map:
    url: ${MAP_SERVICE_URL:http://localhost:8083}

logging:
  level:
    web: debug
